version: '2'

services:
    node:
        build: .
        image: substrate/ethereum-node
        expose:
            - "30303"
        volumes:
            - connection_data:/tmp
        networks:
            - node_net

volumes:
    connection_data:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: "size=10m"

networks:
    node_net:
        ipam:
            driver: default
            config:
                - subnet: 122.0.0.0/24
                  gateway: 122.0.0.1

